export const UI_TEXT = {
  appTitle: 'AutoCenter Mini Dashboard',
  navListing: 'Listings',
  navForm: 'User Form',
  inventoryBadge: 'Premium Inventory',
  inventoryTitle: 'Vehicle Inventory Dashboard',
  inventoryDescription:
    'Explore curated inventory with fast search, smart sorting, and a modern responsive experience.',
  loadingListings: 'Loading listings...',
  noVehiclesFound: 'No vehicles match your search.',
  genericFetchError: 'Something went wrong while fetching.',
  searchByNameLabel: 'Search by name',
  searchVehiclesPlaceholder: 'Search vehicles...',
  sortByLabel: 'Sort by',
  sortNameAsc: 'Name: A to Z',
  sortNameDesc: 'Name: Z to A',
  sortPriceAsc: 'Price: Low to High',
  sortPriceDesc: 'Price: High to Low',
  formBadge: 'Customer Onboarding',
  formTitle: 'User Input Flow',
  formDescription: 'Submit details with strong validation and clear feedback.',
  formSuccess: 'Form submitted successfully.',
  formSubmit: 'Submit',
  fieldFullName: 'Full Name',
  fieldEmail: 'Email',
  fieldPhone: 'Phone Number',
  fieldPassword: 'Password',
  placeholderFullName: 'Enter your full name',
  placeholderEmail: 'example@email.com',
  placeholderPhone: '+1 000 000 0000',
  placeholderPassword: 'Minimum 6 characters',
  detailsHeading: 'Vehicle Details',
  detailsLoading: 'Loading vehicle details...',
  detailsInvalidId: 'Invalid vehicle id.',
  detailsNotFound: 'Vehicle not found.',
  detailsError: 'Unable to load vehicle details.',
  backToListing: 'Back to listing',
  detailsDescription:
    'This vehicle is sourced from the Auto Center inventory feed and presented in detail view for better review before inquiry.',
} as const
